# -*- coding: utf-8 -*-

import cv2
import numpy as np

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import QThread, QObject, pyqtSignal, pyqtSlot, Qt

import core

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1585, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ekran = QtWidgets.QLabel(self.centralwidget)
        self.ekran.setGeometry(QtCore.QRect(0, 0, 1251, 601))
        self.ekran.setText("")
        self.ekran.setObjectName("ekran")
        self.threshcheck = QtWidgets.QCheckBox(self.centralwidget)
        self.threshcheck.setGeometry(QtCore.QRect(390, 630, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threshcheck.setFont(font)
        self.threshcheck.setObjectName("threshcheck")
        self.kenarcheck = QtWidgets.QCheckBox(self.centralwidget)
        self.kenarcheck.setGeometry(QtCore.QRect(530, 630, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kenarcheck.setFont(font)
        self.kenarcheck.setObjectName("kenarcheck")
        self.kosecheck = QtWidgets.QCheckBox(self.centralwidget)
        self.kosecheck.setGeometry(QtCore.QRect(640, 630, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kosecheck.setFont(font)
        self.kosecheck.setObjectName("kosecheck")
        self.renkcheck = QtWidgets.QCheckBox(self.centralwidget)
        self.renkcheck.setGeometry(QtCore.QRect(740, 630, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.renkcheck.setFont(font)
        self.renkcheck.setObjectName("renkcheck")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(1250, 0, 331, 691))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 331, 567))
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.hsvmin1 = QtWidgets.QSpinBox(self.page)
        self.hsvmin1.setGeometry(QtCore.QRect(150, 20, 51, 22))
        self.hsvmin1.setObjectName("hsvmin1")
        self.hsvmin1.setMaximum(255)
        self.hsvmin2 = QtWidgets.QSpinBox(self.page)
        self.hsvmin2.setGeometry(QtCore.QRect(210, 20, 51, 22))
        self.hsvmin2.setObjectName("hsvmin2")
        self.hsvmin2.setMaximum(255)
        self.hsvmin3 = QtWidgets.QSpinBox(self.page)
        self.hsvmin3.setGeometry(QtCore.QRect(270, 20, 51, 22))
        self.hsvmin3.setObjectName("hsvmin3")
        self.hsvmin3.setMaximum(255)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.hsvmax1 = QtWidgets.QSpinBox(self.page)
        self.hsvmax1.setGeometry(QtCore.QRect(150, 60, 51, 22))
        self.hsvmax1.setObjectName("hsvmax1")
        self.hsvmax1.setMaximum(255)
        self.hsvmax2 = QtWidgets.QSpinBox(self.page)
        self.hsvmax2.setGeometry(QtCore.QRect(210, 60, 51, 22))
        self.hsvmax2.setObjectName("hsvmax2")
        self.hsvmax2.setMaximum(255)
        self.hsvmax3 = QtWidgets.QSpinBox(self.page)
        self.hsvmax3.setGeometry(QtCore.QRect(270, 60, 51, 22))
        self.hsvmax3.setObjectName("hsvmax3")
        self.hsvmax3.setMaximum(255)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.erozyoniter = QtWidgets.QSpinBox(self.page)
        self.erozyoniter.setGeometry(QtCore.QRect(170, 140, 51, 22))
        self.erozyoniter.setObjectName("erozyoniter")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.genisiter = QtWidgets.QSpinBox(self.page)
        self.genisiter.setGeometry(QtCore.QRect(170, 180, 51, 22))
        self.genisiter.setObjectName("genisiter")
        self.blurx = QtWidgets.QSpinBox(self.page)
        self.blurx.setGeometry(QtCore.QRect(140, 280, 51, 22))
        self.blurx.setObjectName("blurx")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.blury = QtWidgets.QSpinBox(self.page)
        self.blury.setGeometry(QtCore.QRect(210, 280, 51, 22))
        self.blury.setObjectName("blury")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 331, 567))
        self.page_2.setObjectName("page_2")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.kenarthresh1 = QtWidgets.QSpinBox(self.page_2)
        self.kenarthresh1.setGeometry(QtCore.QRect(150, 30, 42, 22))
        self.kenarthresh1.setObjectName("kenarthresh1")
        self.kenarthresh1.setMaximum(255)
        self.kenarthresh2 = QtWidgets.QSpinBox(self.page_2)
        self.kenarthresh2.setGeometry(QtCore.QRect(150, 70, 42, 22))
        self.kenarthresh2.setObjectName("kenarthresh2")
        self.kenarthresh2.setMaximum(255)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.kosemax = QtWidgets.QSpinBox(self.page_3)
        self.kosemax.setGeometry(QtCore.QRect(200, 30, 42, 22))
        self.kosemax.setObjectName("kosemax")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.kosekalite = QtWidgets.QSpinBox(self.page_3)
        self.kosekalite.setGeometry(QtCore.QRect(200, 70, 42, 22))
        self.kosekalite.setObjectName("kosekalite")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.koseminmesafe = QtWidgets.QSpinBox(self.page_3)
        self.koseminmesafe.setGeometry(QtCore.QRect(200, 110, 42, 22))
        self.koseminmesafe.setObjectName("koseminmesafe")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.threshust = QtWidgets.QSpinBox(self.page_4)
        self.threshust.setGeometry(QtCore.QRect(120, 20, 42, 22))
        self.threshust.setObjectName("threshust")
        self.threshust.setMaximum(255)
        self.label_12 = QtWidgets.QLabel(self.page_4)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.threshyeni = QtWidgets.QSpinBox(self.page_4)
        self.threshyeni.setGeometry(QtCore.QRect(120, 60, 42, 22))
        self.threshyeni.setObjectName("threshyeni")
        self.threshyeni.setMaximum(255)
        self.toolBox.addItem(self.page_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1585, 26))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(self.menubar)
        self.menuMen.setObjectName("menuMen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVideo = QtWidgets.QAction(MainWindow)
        self.actionVideo.setObjectName("actionVideo")
        self.actionFoto_raf_A = QtWidgets.QAction(MainWindow)
        self.actionFoto_raf_A.setObjectName("actionFoto_raf_A")
        self.actionKamera = QtWidgets.QAction(MainWindow)
        self.actionKamera.setObjectName("actionKamera")
        self.menuMen.addAction(self.actionVideo)
        self.menuMen.addAction(self.actionFoto_raf_A)
        self.menuMen.addAction(self.actionKamera)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        pixmap = QPixmap('ana.png')
        self.ekran.setPixmap(pixmap)

        # Menü İtemleri
        self.actionVideo.triggered.connect(lambda: self.klasorsec(0))
        self.actionFoto_raf_A.triggered.connect(lambda: self.klasorsec(1))
        self.actionKamera.triggered.connect(lambda: self.klasorsec(2))

        #

        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Görüntü İşleyici"))
        self.threshcheck.setText(_translate("MainWindow", "Threshold"))
        self.kenarcheck.setText(_translate("MainWindow", "Kenar"))
        self.kosecheck.setText(_translate("MainWindow", "Köşe"))
        self.renkcheck.setText(_translate("MainWindow", "Renk"))
        self.label.setText(_translate("MainWindow", "HSV Minimum: "))
        self.label_2.setText(_translate("MainWindow", "HSV Maksimum: "))
        self.label_3.setText(_translate("MainWindow", "Erozyon Tekrarı: "))
        self.label_4.setText(_translate("MainWindow", "Genişleme Tekrarı: "))
        self.label_5.setText(_translate("MainWindow", "Blur Çekirdeği:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Renk"))
        self.label_6.setText(_translate("MainWindow", "Threshold 1: "))
        self.label_7.setText(_translate("MainWindow", "Threshold 2: "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Kenar"))
        self.label_8.setText(_translate("MainWindow", "Maksimum Köşe Sayısı: "))
        self.label_9.setText(_translate("MainWindow", "Kalite Seviyesi: "))
        self.label_10.setText(_translate("MainWindow", "Minimum Mesafe: "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Köşe"))
        self.label_11.setText(_translate("MainWindow", "Üst Limit: "))
        self.label_12.setText(_translate("MainWindow", "Yeni Değer: "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Threshold"))
        self.menuMen.setTitle(_translate("MainWindow", "Menü"))
        self.actionVideo.setText(_translate("MainWindow", "Video Aç"))
        self.actionFoto_raf_A.setText(_translate("MainWindow", "Fotoğraf Aç"))
        self.actionKamera.setText(_translate("MainWindow", "Kamera"))


    def klasorsec(self, mod):
        if mod == 0:
            self.klasor = QtWidgets.QFileDialog.getOpenFileName(None, 'Dosya Seç', 'C:\\users\\%username%\\Desktop', "Video Dosyaları (*.mp4)")
            #print(self.klasor[0])
            if self.klasor[0] != "":
                self.threadfonk(self.klasor[0])

        elif mod == 1:
            self.klasor = QtWidgets.QFileDialog.getOpenFileName(None, 'Dosya Seç', 'C:\\users\\%username%\\Desktop',"Resim Dosyaları (*.jpg *.png)")
            #print(self.klasor[0])
            if self.klasor[0] != "":
                self.fotograf(self.klasor[0])

        elif mod == 2:
            self.klasor = 0
            self.threadfonk(self.klasor)


    def fotograf(self, dosya):
        try:
            self.threadvidstop()
            self.threadfotostop()
        except:
            pass
        self.fotomod = core.fotograflar(dosya)
        self.threadfoto = QThread()
        self.fotomod.yolla.connect(self.gosterim)
        self.fotomod.moveToThread(self.threadfoto)
        self.threadfoto.started.connect(self.fotomod.fotoveri)
        self.threadfoto.start()

    def threadfonk(self, mod):
        try:
            self.threadvidstop()
            self.threadfotostop()
        except:
            pass
        self.videomod = core.videolar(mod)
        self.threadvid = QThread()
        self.videomod.yolla.connect(self.gosterim)
        self.videomod.moveToThread(self.threadvid)
        self.threadvid.started.connect(self.videomod.veriakimi)
        self.threadvid.start()

    def threadvidstop(self):
        self.videomod.stop()
        self.threadvid.quit()
        self.threadvid.wait()

    def threadfotostop(self):
        self.fotomod.stop()
        self.threadfoto.quit()
        self.threadfoto.wait()

    def gosterim(self, frame):
        frame = cv2.resize(frame, (1251, 601))
        if self.threshcheck.isChecked():
            thresh = frame.copy()
            thresh = cv2.cvtColor(thresh, cv2.COLOR_BGR2GRAY)
            _, frame = cv2.threshold(thresh, self.threshust.value(), self.threshyeni.value(), cv2.THRESH_BINARY)
            frame = cv2.cvtColor(frame, cv2.COLOR_GRAY2BGR)

        if self.kenarcheck.isChecked():
            frame = cv2.Canny(frame, self.kenarthresh1.value(), self.kenarthresh2.value())
            #rgbImage = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        if self.kosecheck.isChecked():
            shi = frame.copy()
            shi = cv2.cvtColor(shi, cv2.COLOR_BGR2GRAY)
            shi = cv2.goodFeaturesToTrack(shi, maxCorners=self.kosemax.value(), qualityLevel=0.01, minDistance=0.5)
            shi = np.int64(shi)

            for i in shi:
                x, y = i.ravel()
                cv2.circle(frame, (x, y), 2, (0, 255, 0), cv2.FILLED)

        if self.renkcheck.isChecked():
            blurred = cv2.GaussianBlur(frame, (11, 11), 0)
            hsv = cv2.cvtColor(blurred, cv2.COLOR_BGR2HSV)
            frame = cv2.inRange(hsv, (self.hsvmin1.value(), self.hsvmin2.value(), self.hsvmin3.value()), (self.hsvmax1.value(), self.hsvmax2.value(), self.hsvmax3.value()))

        rgbImage = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        h, w, ch = rgbImage.shape
        bytesPerLine = ch * w
        convertToQtFormat = QImage(rgbImage.data, w, h, bytesPerLine, QImage.Format_RGB888)
        p = convertToQtFormat.scaled(1251, 601, Qt.KeepAspectRatio)
        self.ekran.setPixmap(QPixmap.fromImage(p))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
